helper_functions.py, tests/T_to_Tv_tests.ipynb
Add module for converting from measured quantities to QOIs. Right now, this includes a function `helper_functions.T_to_Tv()` that can take a variety of combinations of inputs and convert from measured air temperature into virtual temperature. There are additional functions that perform intermediate calculations that `T_to_Tv()` depends on; these generally come from either Wallace & Hobbs or equations from the NWS, and the source of the equations are noted in the code comments.
You can view `tests/T_to_Tv_tests.ipynb` directly in the browser. This notebook shows how some test data are read (in this case, the PS07 3-m met tower) and how the new functions may be used.
I'm open to adding additional formulations, renaming variable and function names, etc.
=> Temperature conversion utilities

measurements/radar.py
Update `measurements.radar.profiler()` to take `read_scan_properties` as a keyword argument. If True or an existing list of scan types (parsed from the profiler data block header) is provided, then each data block that is read from a file will have its scan properties compared against the existing list of scan types and a unique scan-type ID will be assigned. A new "scan_type" column will be created with the scan-type IDs.
Example use case: TTU radar data for 2013-11-08 has 2 different scan types, 2013-11-09 has 3 different scan types. Resulting data will have "scan_type" identifier to distinguish between the different scans.
=> Add option for radar profiler reader to parse scan info

datawriters.py, wrf/WriteWRFdata2NCDF.wrf.py, wrf/utils.py
- unstagger functions "unstagger2d", "unstagger3d", "unstagger4d" are replaced by one general "unstagger" function that can handle any dimensions
- get_height() had a bug using both 2d and 3d arrays in a calculation. This has been fixed
- a new function get_xyzt_height() has been added to compute the height above ground level for every timestamp, returning a 4d array. The function get_height() has been renamed to get_xyz_height() to reflect that it returns a 3d array.
=> Some updates and cleanup for wrf.utils

plotting.py
E.g., when a dataset comes from a precursor with simulation times rather than actual timestamps
=> Handle numeric times in plot_profiles()

plotting.py
Avoid IndexError when number of plotted lines is larger than the length of the default color list by wrapping the list to get a cycle.
=> Wrap default colors to get color cycle

plotting.py
The default fieldlimits argument was an empty dictionary. However, a dictionary is a mutable object, so the first time a function is called, the default argument to fieldlimits is actually a reference to the empty dict. If the dictionary is then modified throughout the course of that first function evaluation, the default argument (the original "pointer" to the dictionary) would point to this modified dictionary, which is not empty anymore. This happened for example in `plot_timeheight`, where fieldlimits are calculated based on data limits if no fieldlimit is specified. After the first evaluation of `plot_timeheight`, the default fieldlimit argument was not an empty dict but contained the fieldlimits computed in that first function evaluation.
This bug is fixed by setting the default …
=> Fix bug in default fieldlimits

coupling/sowfa.py
For cleaner interfacing between SOWFA precursor and finite-domain simulations, e.g., using `sourceHistory_to_drivingForce.ipynb`. 
- Allow `dateref` kwarg to not be specified when initializing the InternalCoupling class--this is not applicable for idealized cases
- Modify `write_timeheight()` so that 
```
timeheight_to_sowfa = InternalCoupling(outputdir,df,dateref)
timeheight_to_sowfa.write_timeheight('forcingTableMomentum',xmom='Fx',ymom='Fy',zmom='Fz')
timeheight_to_sowfa.write_timeheight('forcingTableTemperature',temp='Ft')
```
produces the expected result (with 'forcingTableMomentum' only containing momentum sources, and 'forcingTableTemperature' only containing temperature sources). Previously, all four fields were written into both forcingTable* files.
=> Generalize internal coupling

plotting.py
Make datetime axis consistent:
- always plot date _and_ time at major ticks (behavior changed after matplotlib v3.1.0)
- always plot times starting from midnight
FYI @DriesAllaerts
=> Hotfix: update plotting._format_time_axis()

dataloaders.py
To handle not only a series of datetime subdirectories, but time directories (e.g.., openfoam simulation times) as well. Add `file_filter` option to provide similar functionality as the other `dataloader.read_*()` functions.
=> Generalize dataloaders.read_date_dirs()

plotting.py
- Different sets of `standard_fieldlabels` and `standard_spectrumlabels` are now available, e.g., if you want to have a custom set of variable names and units to be used in labeling plots. 
- A custom format can specified when plotting with the `plot_local_time` option.
=> Add plot formatting options

wrf/preprocessing.py
Add python code to replace old csh scripts. Currently implemented:
- NCEP FNL Operational Analysis
- ERA Interim Reanalysis
Sample usage:
```python
import pandas as pd
from mmctools.wrf.preprocessing import ERAInterim
datetimes = pd.date_range(start='2019-03-26 00:00',
end='2019-03-27 12:00',
freq='21600s')
icbc = ERAInterim()
icbc.download(datetimes)
```
=> WRF reanalysis dataset retrieval tools

wrf/landuse.py
For collecting information from a LANDUSE.TBL file and putting it into a more usable format. 
Example:
`landuse = LandUseTable('/path/to/WRF/run/LANDUSE.TBL')`
```
Reading OLD
Reading USGS
Reading MODIFIED_IGBP_MODIS_NOAH
Reading SiB
Reading LW12
Reading MODIS
Reading SSIB
```
For single-season definitions, properties are stored in a single-index dataframe:
`print(landuse['LW12'])`
```
albedo	soil_moisture_availability	surface_emissivity	roughness_length	thermal_inertia	snow_cover_effect	surface_heat_capacity	description
1	0.2	0.3	0.85	0.1	4	2	2.08e+06	Land
2	0.08	1	0.98	0.0001	6	0	9e+25	Water
3	0.7	0.95	0.95	0.05	5	0	9e+25	Snow or Ice
```
For definitions with multiple seasons, properties are stored in a multi-index dataframe:
`print(landuse['USGS'].head())`
```
albedo …
```
=> Add landuse submodule

plotting.py
Specifying timelimits as a tuple of strings can raise:
```AttributeError: 'numpy.str_' object has no attribute 'toordinal'```
and ultimately:
```ConversionError: Failed to convert value(s) to axis units```
This is traced back to
`ax[-1].set_xlim(timelimits)` in `_format_time_axis`.
Tested with numpy 1.18.1 and matplotlib 3.1.3 (conda-forge)
=> Fix for ConversionError when specifying timelimits

helper_functions.py
ABL height estimates based on:
1. temperature gradient threshold
2. vertical heat flux minima (for convective boundary layers)
3. vertical momentum flux minima (for stable boundary layers)
For diurnal cases, recommend applying moving median filter on resulting estimates; then, blending between methods 2 and 3, using method 3 where method 2 vanishes.
=> Add helper_functions.estimate_ABL_height()

wrf/utils.py
Add new `unstagger` kwarg (True by default) that also depends on an additional optional `staggered_vars` option. This affects calls to `Tower.to_dataframe()` for which no interpolation to specified heights is requested. For height interpolation, staggering is handled by separately interpolating staggered and unstaggered data. 
A slight performance enhancement should also have been achieved. Dataframes are now created by a data dictionary and time-height multi-index. Previously, this was accomplished by supplying 2-D data arrays, creating the dataframe in a wide (unstacked) format (time index and with multiindex columns), and then doing a stack operation. Not sure why this was a good idea at the time...
=> Properly handle staggered tslist profiles in Tower.to_dataframe()

plotting.py
In the situation where a dataframe to be plotted has both "datetime" and "Time" indices (e.g., corresponding to timestamps and simulation time, respectively), the time index is expected to be "datetime". Here we update `dimension_names['time']` to have "datetime" come first.
=> Put 'datetime' first in list of time dimension_names

coupling/sowfa.py
Quick edit to not restrict InternalCoupling data to have pandas DateTimeIndex or TimedeltaIndex
=> Add support for initializing with InternalCoupling() pandas indices

plotting.py
Based on public-domain code from https://gist.github.com/ycopin/3342888 with edits from @phawbeck 
Updates:
- Add `stdevticks` option to `TaylorDiagram.__init__()` -- @phawbeck !
- Add `TaylorDiagram.set_xlabel()` (stdev axis)
- Add `TaylorDiagram.set_alabel()` (azimuthal correlation axis)
=> Implement mmctools.plotting.TaylorDiagram

plotting.py
Example usage for overlaying multiple model/reference data levels on the same plot:
```python
fig = plt.figure(figsize=(11,8))
td = TaylorDiagram(1.0, label='lidar', fig=fig,
srange=(0,1.6), extend=False,
normalize=True,
corrticks=[0,.1,.2,.3,.4,.5,.6,.7,.8,.9,.95,.99],
#minorcorrticks=np.arange(0.05,0.9,0.1),
stdevticks=np.arange(0.2,1.6,0.2),
labelsize='x-large')
selected_tower = dict(nx=1, ny=1)
stats = {}
pthandles = {}
for case in cases.keys():
reanalysis,starttime = case
descstr = starttime.strftime('{:s} init %Y%m%d %HZ'.format(reanalysis))
stats[case] = pd.DataFrame(index=refheights, columns=['std_norm','R2'], dtype=float)    
for z in refheights:
ref_wspd = ref['wspd'].xs(z, level='height')
refstdev = ref_wspd.std()
model_wspd = …
```
=> Improve TaylorDiagram plotting class

plotting.py
Address an issue that occasionally arises in which a subplot from `plot_timehistory_at_height` will having missing gridlines where major and minor xaxis lines are coincident.
=> Fix gridlines

plotting.py
- Provide useful message instead of ValueError when invalid plot times are selected
- Implement `plot_local_time` and associated `local_time_offset` kwargs
- If `plot_local_time` is not False, then specified times are local times and the `plot_local_time` may either be set to True or a format string
=> Improve time handling for plot_profile()

mmctools/wrf/utils.py
Moved import inside mmctools.wrfout_seriesReader() because this is the only place it is used.
=> Allow use of mmctools.wrf without wrf-python module

mmctools/coupling/sowfa.py
Example usage:
```python
to_sowfa = InternalCoupling(outdir, df_hist, dateref=simstart)
to_sowfa.write_BCs('surfaceTemperatureFluxTable', fieldname='hfx')
to_sowfa.write_BCs('qwallTable', fieldname=[0,0,'hfx'])
```
for which 'hfx' is a column in the time-history dataframe `df_hist`
FYI @DriesAllaerts
=> Add option to write out a timehistory of vectors for SOWFA InternalCoupling

mmctools/helper_functions.py, mmctools/wrf/utils.py
- Fix momentum flux calc in `mmctools.helper_functions.model4D_calcQOIs()`
- `tslist` output processing improvements: increase date-time precision (1s to 1ms) and allow passing of optional kwargs to `mmctools.wrf.utils.tsout_seriesReader()`
=> Hotfixes for perturbations study

mmctools/wrf/utils.py
Related to the rounding bug in #112
=> Fix single-precision issue in `Tower.to_dataframe()` when `time_step` is provided

setup.py
While working with @phawbeck, we encountered some strange errors with the `pickle` module that were resolved by updating to the latest `pandas` version.
=> Allow latest versions of packages

mmctools/plotting.py
Default is True to retain backwards compatibility; if False and a height from outside the data range is requested, a warning message will be printed instead of plotting the extrapolated history. FYI @DriesAllaerts
=> Add 'extrapolate' option to plot_timehistory_at_height()

mmctools/wrf/utils.py
- add `temp_var` option to handle auxiliary output for MMC that has a different variable name for moist potential temperature (`T` instead of `THM`)
- add `use_dimension_coords` option to facilitate and expedite xarray operations
- clean up vertical clipping code
Tested on auxout data with/without `specified_heights`, `hlim_indx`, and `use_dimension_coords`.
=> Update wrfout series reader

environment.yaml, mmctools/helper_functions.py, setup.py
Functions for Terrain Ruggedness Index (TRI) and Vector Ruggedness
Measure (VRM) accept lists, arrays, and xr.Dataset and DataArray.
Returned are arrays with the respective TRI or VRM values. Both of
these calculations rely on a height array and a specified window.
=> Add functions for TRI and VRM

mmctools/helper_functions.py
This uses scipy's ```generic_filter``` function to speed up the TRI calculation by about 2.5x and VRM by 16x (tested with window=3).
=> TRI and VRM were pretty slow

mmctools/helper_functions.py
Allows the calculation of spectras for several variables at once.
Example:
```
calc_spectra(dataset,
var_oi=['u', 'v' ,'w', 'wspd'],
spectra_dim='datetime',
level_dim='height',
)
```
=> Allow spectras to be calculated for a list of variables

mmctools/helper_functions.py
Added the ability to compute cross PSD to `calc_spectra`. Now, on top of `var_oi`, we have `xvar_oi`, where you can request pairs of variables as tuples. See docstrings for description and example call.
Everything modified is still backward compatible.
=> Add cross PSD computation capability

mmctools/helper_functions.py
Fix on the cross PSD computation returning the absolute value instead of just the real part. It's been siting in my branch for several months now and has been tested on several different datasets (SOWFA and WRF).
=> Cross PSD fix

mmctools/coupling/sowfa.py
Successfully tested `mmctools.coupling.sowfa.BoundaryCoupling`.
Example snippet
```
yzplane = ds.isel(y=100)
bd = BoundaryCoupling('bndrydata',yzplane,'west',dateref='2000-01-01')
bd.write({'U':'U','V':'V','W':'W','T':'T'}, gzip=True)
```
=> Fix time coord bug for BoundaryCoupling
