a2e-mmc/mmctools

dataloaders.py, met_mast.py, plotting.py, remote_sensing.py
@jsauer-NCAR Here's the code structure I outlined in our last in-person meeting.
=> Add stubs for new code

wrf/utils.py
- Python3 compatibility
- Add wrf_times_to_datetime() function to preserve datetime information in native numpy form
- Remove import of unused modules
- Eliminate subprocess usage
=> Updates to wrf/utils

measurements/radar.py
Migrated code from NWTC/dadtatools/remote_sensing.py to provide `radar.profiler()` data reader for winds and temperature data. Cleaned up the code and added some more documentation.
=> ESRL wind profiler data reader

datawriters.py
Add `write_to_netCDF` from Amy
=> netcdf writer

plotting.py
Includes a bugfix in determining number of rows and columns in specified ax
=> Allow user-specified ax to be a list

helper_functions.py
=> Add helper function to calculate wind speed/direction from u,v

helper_functions.py
@DriesAllaerts, as we had discussed.
=> Implement theta(T,p) convenience function

plotting.py
- Fix height labels when ncols>1
- Add fieldorder option
- If colorbar array has size 1, return actual colorbar object instead of array.
=> Some improvements to plot_timeheight

helper_functions.py
Additions of helper_functions for calculating spatial spectra and distribution statistic from model-4D xarray datasets
=> Spatial spectra and statistics helper routines

wrf/utils.py
=> Fix bugs in wrf/utils.py

wrf/utils.py
Fixed bug, made `extract_column_from_wrfdata` more robust
=> Hotfix: wrf.utils

helper_functions.py
for more control over rolling/resample operations.
=> Add kwargs to helper_functions.covariance()

helper_functions.py
These pertain to the calculations of saturation vapor pressure and saturation mixing ratio, e_s and w_s, respectively.
=> Update notes and comments in helper_functions.py

wrf/utils.py
Update the `to_dataframe()` function in the `wrf.utils.Tower`class.
- add agl option to allow input/output of heights above ground level (AGL) 
- updated docstring
=> Update WRF utils Tower class

coupling/terrain.py
In coupling.terrain.SRTM.download(), to deal with cryptic `subprocess.CalledProcessError`
=> Automatically create directory path if needed

plotting.py
A tuple of dates may be specified instead of specific times (with the "times" keyword).
=> Add timerange option to plot_profile

environment.yaml
Usage:
```
conda create -n mmc  # to create a new environment (optional)  
conda activate mmc  # or conda activate my_existing_env
conda env update --file environment.yaml
```
=> Add conda environment file

plotting.py
Quick modification to allow list/tuple instead of bool for `labelsubplots` kwarg to all plotting functions.
=> Plotting feature: specify subplot label position

wrf/preprocessing.py
Example usage:
```
import pandas as pd
from mmctools.wrf.preprocessing import ERA5
datetimes = pd.date_range(start='2019-12-25 12:00',
end='2019-12-27 00:00',
freq='1h')
icbc = ERA5()
icbc.download(datetimes)
```
=> Add ERA5 class for interacting with Copernicus CDS

wrf/utils.py
Add an optional argument `hlim_ind = None` to the function `wrfout_seriesReader` from `mmctools.wrf.utils`. The idea is that if the user doesn’t provide a value for `hlim_ind`, the function works as before (so people who have developed code using this tool won’t have their code break). But if the user is experiencing memory errors as I was, an easy way to solve this problem is to ignore the model gridcells located far from the surface (since we only have measurements up to 200 m anyway).
=> Add memory error workaround to wrfout_seriesReader

helper_functions.py
More robust version copied from https://github.com/ewquon/windtools/commit/759b6059342ae018e95d900f188072b507b4c675
=> Update function to perform power-law fitting

mmctools/coupling/terrain.py
FYI @rthedin 
* BUG FIX: Handle output paths with spaces so that `elevation.clip()` doesn't fail
* Add more helpful error message when calling `download()`
* Handle new USGS ISO XML metadata format
* Add new `mmctools.coupling.terrain.calc_slope()` function
=> Update terrain module

mmctools/plotting.py
Fix bug introduced by https://github.com/a2e-mmc/mmctools/pull/117
=> Fix extrapolation check for timeseries plots

mmctools/wrf/utils.py
To interpolate to heights above ground level (AGL); warn if NaNs are found after calling `wrf.interplevel()`
Tested with:
```
heights = np.arange(5,1010,100.)
wrfout_seriesReader('auxout','mmc_d02*',specified_heights=heights,agl=True,
temp_var='T',use_dimension_coords=True,
irange=(94,96), jrange=(82,84),
extra_vars=['MUU','MUV','RU_TEND_PGF','RV_TEND_PGF'])
```
=> Add `agl` option to `wrfout_seriesReader()`

mmctools/wrf/preprocessing.py
Silly mistake. Adding xarray import.
=> Xarray needed for OverwriteSST

mmctools/helper_functions.py, mmctools/wrf/preprocessing.py, mmctools/wrf/utils.py
The calc_spectra function is intended to replace the model4D_*spectra functions. Near-term goal is to add co-spectra capability to it.
The netCDF times function simply grabs time values from netCDF files so that pre-processing can have an overwrite-sst functionality.
=> Adding calc_spectra function and preprocessing change

mmctools/plotting.py
=> Recognize 't' as time dimension

mmctools/wrf/utils.py
FYI @ewquon @phawbeck 
Function to read the wrf slice output that has been added to the mmc version of WRF.
User can either specify a list of variables to be read (all slice heights in variables), choose all "slices" variables at specified heights, or choose surface-only variables (e.g. UST, HFX).
This function is required for latest reader being pushed for FINO offshore microscale analysis of WRF.
=> add wrfout_slices_seriesReader function

mmctools/coupling/terrain.py
Adding 3 functions related to topography metrics. 
Example for SE winds:
=> Add some terrain metrics (Sx, Sb, TPI)

mmctools/coupling/terrain.py
Improve shelterness index Sx calculation and add `readSTL` function.
=> Terrain manipulation improvement

mmctools/wrf/preprocessing.py, mmctools/wrf/utils.py
Making it more flexible for reading in the restarts (or using if there are no restarts) and for setting the simulation start time.
=> Adding flexibility to tsout_seriesReader

mmctools/helper_functions.py
This time it's dev --> dev
@phawbeck
=> bug fix in model4D_pdfs function in helper_functions.py
